deployment:
  name: sender-service
  replicaCount: 1
  containers:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 4Gi
  port: 1025
  mongo:
    uri: mongodb://mongo-0.mongo:27017/
    database: sender-service
  kafka:
    bootstrap:
      server: 10.8.15.224:9092
service:
  target:
    port: 1025
actuator:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 8074
env:
  JDK_JAVA_OPTIONS: "-Xmx3584M"