apiVersion: v1
kind: Service
metadata:
  name: sender-service-serv
spec:
  selector:
    app: sender-service-app
  ports:
    - protocol: TCP
      port: {{.Values.deployment.port}}
      targetPort: {{.Values.service.target.port}}
